services: # Defines all of our services or containers
  appservice: # Service definition
    build: ./product-service/src #Builds the docker file in the directory
    ports:
      - "5000:5000"

  web:
    build: ./nginx
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    container_name: db-mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=password